import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css"
import "./../../node_modules/mdb-ui-kit/css/mdb.min.css"
import "./../../node_modules/bootstrap-icons/font/bootstrap-icons.css"
import { Providers } from "@/rtk/provider/providers";
import { Navbar } from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
